- name: Delete nginx in ubuntu
  hosts: dbserver
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
      notify: Start service
  handlers:
    - name: Start service
      service:
        name: nginx
        state: started

- name: Delete nginx from amazon
  hosts: webserver
  become: true
  tasks:
    - name: Uninstall nginx from amazon
      yum:
        name: nginx
        state: present
      notify: Start service2
  handlers:
    - name: Start service2
      service:
        name: nginx
        state: started
