- hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

      notify: Start nginx
  handlers:
    - name: Start nginx
      apt:
        service: nginx
        state: started
