- name: Add nginx in ubuntu
  hosts: dbserver
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

- name: Add nginx from amazon
  hosts: webserver
  become: true
  tasks:
    - name: install nginx from amazon
      yum:
        name: nginx
        state: present
