- hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        become: true
        notify: Start nginx
  handlers:
    - name: Start nginx
      become: true
      apt:
        service: nginx
        state: started
