- hosts: webservers
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
      notify: Start nginx
  handlers:
    - name: Start nginx
      service:
        name: nginx
        state: started
