- name: Delete nginx in ubuntu
  hosts: dbserver
  become: true
  tasks:
    - name: Uninstall nginx
      apt:
        name: nginx
        state: absent

- name: Delete nginx from amazon
  hosts: webserver
  become: true
  tasks:
    - name: Uninstall nginx from amazon
      yum:
        name: nginx
        state: absent
