---
- hosts: webservers
  become: true
  tasks:
   - name: Install Package git software
     apt: name=git state=present
   - name: Install Package
     apt: name=httpd state=present
   - name: Start httpd service
     service: name=httpd state=started
